### PR TITLE
Make explanation on limits of live-time more clear

### PR DESCRIPTION
**Pull request by webwurst**
/cc @marians

### CODE REVIEW

**Comment by marians** [comment]
Are you still planning to change the URL?

**Comment by webwurst** [comment]
I just wanted to change the URL to [#own-domain-name](https://docs.giantswarm.io/reference/swarm-json/#own-domain-name), but result looks bad, upper part is hidden by our site-navigation.

What do you think?

**Comment by marians** [comment]
I think you should do the change anyway and we try to fix the y offset problem in the docs CSS/JS code. We have this issue in several places.

**Comment by webwurst** [comment]
Ok, I have tested this again. Could merge it now.
/ping @marians

**Comment by marians** [comment]
Shame, this went stale. LGTM.

**Pull request merged**
